### PR TITLE
Moved require('exit') to bin\lesshint

### LINKED ISSUE #281: Allow an onExit other than the exit package
When trying to run `lesshint` via...

```javascript
const lesshint = require('lesshint/lib/cli');
const settings = { /* ... */ };

lesshint(settings)
    .then(statusCode => console.log(`Finished with status ${statusCode}`})
    .catch(error => console.error(`Error: ${error}`));
```

...nothing gets logged in the happy case because [exit](https://www.npmjs.com/package/exit) is called at the end.

If we change one line in cli.js, it becomes possible to provide a custom `onExit` callback:

```javascript
    exitPromise.always(function (status) {
        // exit(status.valueOf());
        (program.onExit || exit)(status.valueOf());
    });
```

it would be possible to provide a custom onExit.

```javascript
const settings = {
    onExit: () => {}
};
```

Required for https://github.com/lesshint/lesshint/issues/278.

In case you're wondering why I'm not using the recommended `require('lesshint')`: it's to get all the features of the CLI without having to spawn subprocesses. A more complicated alternative would be to refactor out the non-`exit`-y parts of the CLI from `cli.js`.

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
This allows consumers of the CLI function to not randomly close when the exit package is called.

Fixes #281.

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
I'll push a second commit that, in addition to fixing the build breaks, changes the CLI to not interact with an onExit at all. Instead `bin/lesshint` willl do that logic.

File: lib/cli.js [hunk 1]
```diff
@@ -16,15 +15,15 @@ var EXIT_CODES = {
     CONFIG: 78
 };
 
-module.exports = function (program) {
+module.exports = function (program, onExit) {
```
Comment (shellscape) [inline lib/cli.js]: ehhh thoughts on emitting an event instead @jwilsson @kokarn ?

File: bin/lesshint [hunk 2]
```diff
@@ -22,4 +23,6 @@ program
     .option('-x, --max-warnings [int]', 'Number of warnings to trigger nonzero exit code, defaults to 0')
     .parse(process.argv);
 
-cli(program);
+cli(program).always(function (status) {
+    exit(status.valueOf());
```
Comment (jwilsson) [inline bin/lesshint]: I say we use `process.exitCode` instead. We only used `exit` to work around some strange output issue in an old Node version.

**Comment by JoshuaKGoldberg** [comment]
Re the failing coverage: would you like me to add a `test/bin.js` that exercises `bin/lesshint`?

**Comment by jwilsson** [comment]
@JoshuaKGoldberg Sure, that would be great! No rush :)
