### PR TITLE
Final 3.0 CLI touches

### LINKED ISSUE #321: Max-Warnings Config Issue
**Which version of `lesshint` are you using?** 2.4.0

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**
CLI for testing. package.json run command in Node.js app

**What's your `.lesshintrc` configuration?** Default

**If you're reporting a bug, please show us some code that's failing.**
`lesshint --max-warnings=-1 ./path_to/styles/

**What did you expect to happen?**
I was expecting my build to succeed regardless of how many warnings I had.

**What's the actual result?**
I get an exit code of 1 and I received the following error when I ran the previous code:
`error: unknown options '-1'`

While I could use a positive integer for the time being, it would be nice to know what I am doing incorrectly to receive this error or for it to be corrected to work as expected.

### PR DESCRIPTION
**Pull request by jwilsson**
* Reject `Runner` with real `Error`s.
* Fix handling of `--max-warnings=-1`. Closes #321.
* Fix a minor refactor typo with custom linters.

**Which issue, if any, does this resolve?**
#321 among others.

**Is there anything in this PR that needs extra explaining or should something specific be focused on?**
@kokarn Is this what you had in mind? Hope I didn't step on any toes 😬

### CODE REVIEW

File: lib/runner.js [hunk 1]
```diff
@@ -98,10 +105,10 @@ class Runner {
                 }, 0);
 
                 if (warnings > maxWarnings) {
-                    return reject({
-                        message: '',
-                        status: EXIT_CODES.WARNING
-                    });
+                    return reject(new RunnerError(
+                        '',
```
Comment (kokarn) [inline lib/runner.js]: Can't we avoid this somehow?

Comment (jwilsson) [inline lib/runner.js]: Are you suggesting we put a message there? Or something else?

Comment (kokarn) [inline lib/runner.js]: Not sure what to do, just don't like passing empty messages I guess. 
Can't we have a default just to ease my mind or will that break something?

I guess it's stuff like ```if( error.message )``` that scares me a bit.

Comment (jwilsson) [inline lib/runner.js]: I don't wanna unnecessary output in case someone's piping the output somewhere else, reporters will already have printed everything that's needed.

Comment (kokarn) [inline lib/runner.js]: Hmm, I guess that makes sense. Just leaves me with a funny feeling.
